name: Firebase deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Run deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js application
        uses: actions/setup-node@v4
        with:
          version: latest
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Make build
        run: npm run build

      - name: Doing deploy
        run: npm run deploy
