name: Firebase deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Run deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js application
        uses: actions/setup-node@v4
        with:
          version: latest
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Make build
        run: npm run build

      - name: make deploy
        run: npm run deploy
        env: 
          FIREBASE_TOKEN: 1//0huhL9RQ-idYfCgYIARAAGBESNwF-L9IrNSZeGlVNsCzHAZvOImqBh0kayGTdap29uYiwjMCZzRjshVL-6nv_T4tm6TnW0qhRO9o